version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=blooddonation_52h8_user
      - POSTGRES_PASSWORD=KfibAha77tx16R7wvvuICRFZCsJxC8Jh
      - POSTGRES_DB=blooddonation_52h8
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data  