# Generated by Django 3.2.12 on 2023-08-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='default.jpg', upload_to='profile_pic')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('bloodgroup', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('number', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=20)),
                ('village', models.CharField(max_length=30)),
                ('mandal', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('status', models.CharField(default='False', max_length=10)),
            ],
            options={
                'db_table': 'blooddonation_donors',
            },
        ),
    ]
