# Generated by Django 3.2.12 on 2022-10-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooddonation', '0002_auto_20221027_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
